acme.app.upload:
    path: /media/upload
    defaults:
        _controller: "AcmeAppBundle:Api:upload"
    methods: [POST]

acme.app.post:
    path: /post/event
    defaults:
        _controller: "AcmeAppBundle:Api:post"
    methods: [POST]

acme.app.get:
    path: /get/event
    defaults:
        _controller: "AcmeAppBundle:Api:get"
    methods: [GET]

acme.app.app_post:
    path: /submit/event
    defaults:
        _controller: "AcmeAppBundle:Api:submit"
    methods: [POST]